/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[172.697, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PineTree_5_1.geometry} material={materials.PineTree_Bark} />
        <mesh geometry={nodes.PineTree_5_2.geometry} material={materials.PineTree_Leaves} />
      </group>
      <group position={[176.259, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PineTree_4_1.geometry} material={materials.PineTree_Bark} />
        <mesh geometry={nodes.PineTree_4_2.geometry} material={materials.PineTree_Leaves} />
      </group>
      <group position={[181.365, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PineTree_3_1.geometry} material={materials.PineTree_Bark} />
        <mesh geometry={nodes.PineTree_3_2.geometry} material={materials.PineTree_Leaves} />
      </group>
      <group position={[184.402, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PineTree_1_1.geometry} material={materials.PineTree_Bark} />
        <mesh geometry={nodes.PineTree_1_2.geometry} material={materials.PineTree_Leaves} />
      </group>
      <group position={[188.076, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PineTree_2_1.geometry} material={materials.PineTree_Bark} />
        <mesh geometry={nodes.PineTree_2_2.geometry} material={materials.PineTree_Leaves} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
